/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: SeverDoes3D (https://sketchfab.com/SeverDoes3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/office-assets-16c1a779bb0a4055a26367741d39e059
Title: Office - Assets
*/

import React, { useRef } from 'react'
import { useGLTF, Html } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('../../public/Scene/scene.gltf')
  return (
    <group {...props} dispose={null} position={[1.5, -0.7, 0]} rotation={[0.3, -1.36, 0]} scale={1.9}>
        <mesh geometry={nodes.Object_16.geometry} material={materials.M_Computer_2048} position={[0.103, 0.91, 0.502]} rotation={[0, -0.269, 0]} />
        <Html
          transform
          scale={5}
          position={[-230, 0, -98]}
          rotation={[0,1,0]}
          distanceFactor={5.5}
        >
            <iframe width="681px" height="518px" src="https://packard-belle.netlify.app/" />
        </Html>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
