/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: SeverDoes3D (https://sketchfab.com/SeverDoes3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/office-assets-16c1a779bb0a4055a26367741d39e059
Title: Office - Assets
*/

import React, { useRef } from 'react'
import { useGLTF, Html } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('../../public/Scene/scene.gltf')
  return (
    <group {...props} dispose={null} position={[1.5, -0.7, 0]} rotation={[0, -1.36, 0]} scale={1.9}>
      <group position={[-0.051, 0.743, 0.876]} rotation={[0, -0.736, 0]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.M_Cactus_1024} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.M_Cactus_1024} position={[0.01, 0.122, 0.014]} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.M_Cactus_1024} position={[0.001, 0.123, -0.001]} />
      </group>
      <group position={[0.035, 0.743, 1.904]} rotation={[-Math.PI, 1.358, -Math.PI]}>
        <mesh geometry={nodes.Object_70.geometry} material={materials.M_TapeRecorder_1024} />
        <mesh geometry={nodes.Object_71.geometry} material={materials.M_TapeRecorder_Tape_Rotors_Glass_1024} />
      </group>
      <group position={[0.996, 0.565, 0.619]} rotation={[-3.126, -1.002, -1.576]}>
        <mesh geometry={nodes.Object_101.geometry} material={materials.M_Clipboard_Notepad_1024} />
        <mesh geometry={nodes.Object_103.geometry} material={materials.M_Clipboard_Notepad_1024} position={[0.006, -0.034, 0.001]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.381} />
      </group>
      <group position={[-0.039, 0.743, 1.563]} rotation={[0, 0.454, 0]}>
        <group position={[0, 0.061, 0]} rotation={[0, 0, 0.811]}>
          <group position={[0, 0.118, 0]} rotation={[0, 0, -0.976]}>
            <group position={[0, 0.279, 0]} rotation={[0, 0, -0.491]}>
              <group position={[0, 0.366, 0]} rotation={[0, 0, -0.603]}>
                <mesh geometry={nodes.Object_117.geometry} material={materials['M_Lamps_CCTV_2048.001']} />
                <mesh geometry={nodes.Object_119.geometry} material={materials['M_Lamps_CCTV_2048.001']} position={[0, 0.083, 0]} />
              </group>
              <mesh geometry={nodes.Object_115.geometry} material={materials['M_Lamps_CCTV_2048.001']} />
            </group>
            <mesh geometry={nodes.Object_113.geometry} material={materials['M_Lamps_CCTV_2048.001']} />
          </group>
          <mesh geometry={nodes.Object_111.geometry} material={materials['M_Lamps_CCTV_2048.001']} />
        </group>
        <mesh geometry={nodes.Object_109.geometry} material={materials['M_Lamps_CCTV_2048.001']} />
      </group>
      <mesh geometry={nodes.Object_10.geometry} material={materials.M_Computer_2048} position={[0.488, 0.743, 0.925]} rotation={[0, 0.168, 0]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.M_Computer_2048} position={[0.533, 0.743, 0.53]} rotation={[0, -0.169, 0]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.M_Computer_2048} position={[0.061, 0.743, 0.472]} rotation={[0, -0.387, 0]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.M_Filebox_1024} position={[-0.084, 0.743, 1.283]} rotation={[0, 1.531, 0]} scale={[1.096, 1, 1]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.M_Filebox_1024} position={[-0.075, 0.743, 1.398]} rotation={[-Math.PI, 1.512, -Math.PI]} scale={[1.096, 1, 1]} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.M_Filebox_1024} position={[-0.084, 0.743, 1.281]} rotation={[0, 1.531, 0]} scale={[1.096, 1, 1]} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.M_Filebox_1024} position={[-0.075, 0.743, 1.398]} rotation={[-Math.PI, 1.512, -Math.PI]} scale={[1.096, 1, 1]} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.M_Office_PinBoard_Photo_Notepad_1024} position={[0.363, 0.743, 1.741]} rotation={[-0.005, 1.388, 0.005]} scale={[0.381, 0.137, 0.381]} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.M_Office_PinBoard_Photo_Notepad_1024} position={[-0.034, 0.743, 1.116]} rotation={[Math.PI / 2, 0, -1.814]} scale={0.381} />
      <mesh geometry={nodes.Object_54.geometry} material={materials.M_Sigarettes_512} position={[0.481, 0.747, 1.504]} rotation={[1.002, 0.422, 0.998]} scale={0.5} />
      <mesh geometry={nodes.Object_56.geometry} material={materials.M_Sigarettes_512} position={[0.382, 0.752, 1.511]} rotation={[Math.PI, -1.189, -1.886]} scale={0.5} />
      <mesh geometry={nodes.Object_58.geometry} material={materials.M_Sigarettes_512} position={[0.487, 0.743, 1.35]} />
      <mesh geometry={nodes.Object_60.geometry} material={materials.M_Sigarettes_512} position={[0.446, 0.764, 1.309]} rotation={[-1.448, -0.189, -2.328]} scale={0.5} />
      <mesh geometry={nodes.Object_62.geometry} material={materials.M_Sigarettes_512} position={[0.53, 0.766, 1.406]} rotation={[-1.697, -0.143, 0.343]} scale={0.5} />
      <mesh geometry={nodes.Object_64.geometry} material={materials.M_Sigarettes_512} position={[0.487, 0.752, 1.35]} scale={[1, 0.45, 1]} />
      <mesh geometry={nodes.Object_66.geometry} material={materials.M_Sigarettes_512} position={[0.451, 0.752, 1.464]} rotation={[0, -0.571, 1.574]} scale={0.5} />
      <mesh geometry={nodes.Object_68.geometry} material={materials.M_Table_2048} position={[0.213, 0.006, 1.171]} />
      <mesh geometry={nodes.Object_73.geometry} material={materials.M_TapeRecorder_Tape_Rotors_Glass_1024} position={[0.445, 0.743, 1.958]} rotation={[0, 0.361, 0]} />
      <mesh geometry={nodes.Object_105.geometry} material={materials.M_Clipboard_Notepad_1024} position={[0.235, 0.743, 1.171]} rotation={[0, 0.319, Math.PI / 2]} />
      <mesh geometry={nodes.Object_107.geometry} material={materials.M_OfficeStool_Bin_2048} position={[0.923, 0.008, 0.77]} rotation={[-Math.PI, -0.416, -Math.PI]} scale={[1.235, 1, 1.235]} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
